server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL do Eureka Server
spring:
  application:
    name: devhotel-api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
